### ISSUE TITLE
nodejs8: failed with npm but works with yarn

### ISSUE THREAD

**Issue by lorvent** [nstungcom/gulp-starter-kit#1]
Hello,

**preface:** i have built my own gulp-starter-kit long back but i have used `laravel-elixir` in it which is deprecated now and thought of building my own,

but then i searched github for many solutions and so far your looks more native to me because of nunjucks and almost everything i need are added.

---

i see that, you have node 10 as required but people like me forced to stay with node8 for many reasons and when i use `yarn` it is installing properly but if i use `npm i` it is not installing.

hope you can workout on this (if possible)

---

and if i have to mention..if it is missing anything..mostly linting, cache busting and markdown support (i don't use markdown anyways in my site)

and good point is: instead of splitting gulp tasks into separate js files, you added everything into gulpfile.js which is very helpful for beginners (advanced guys may differ with me)

Thank you for your time.

**Comment by nstungcom** [comment]
Hi,

thanks for your feedback 😃

About `npm i` install nothing might be fixed by this [commit](https://github.com/nstungcom/gulp-starter-kit/commit/0787c658868894dcbfb02229286141d8b83bc3e7). Can you try download the latest release and try again?

Have you heard of [nvm](https://github.com/nvm-sh/nvm)? NVM will let you manage and use difference Node.js versions. Can you list me your Node.js, npm & OS version and maybe an error messages? If I have enough time, I will try to get it working for Node.js 8.

Can you describe a little bit more about markdown e.g use-case?

Almost the projects I'm working with will use a CMS later on like TYPO3, so cache busting is not really a problem for me but i will consider it as a feature. I found a [article](https://cruftlesscraft.com/cache-busting-your-assets#cache-busting-with-gulp) which will be very helpful. If I find the time for it I will try it out. But a PR is very appreciate.

Linting might be added in the future.

**Comment by lorvent** [comment]
Hello, thanks for the response.

i already have latest code and yet no success.

nvm: i am on windows so its not possible to use.

markdown: not a particular usecase and for the product/sites we build...we won't use markdown but having markdown helps a lot when writing html...especially writing a personal blog

i am mainly planning to use it for products/sites we build....but in a later stage...i want to move out of wordpress sites and use some builder for my blogs etc.

linting: good to know.

and i am very much interested in contributing to project aswell if everything goes well.

----

i guess i already told you i have a build system myself... now when i try to copy my nunjucks files into your project...things not working.

there is a big difference between your project and mine...i will try to put them here

| title | yours | mine |
| -- | -- | -- |
| html pages | src | src/pages |
| layouts | src/layouts | templates |
| macros | src/macros | templates/macros |
| partials | src/partials | src/templates/partials |

and because of this...compiling has become a big issue...i tried changing many things in gulpfile but it throws one error or another...i gave up after some time.

hope you can give me a solution for it.

**Comment by lorvent** [comment]
and cache busting for different for static/html sites than for things like craftcms which uses php.

we should use plugin like "gulp-rev-all" which can rename build/prod files

so we don't need to do any server side processing.

**Comment by nstungcom** [comment]
Hi,

I've just released v2.0.0 which support Node.js 8 and a simple documentation which might help you solve the Nunjucks compiling problem.

There is a [nvm-windows](https://github.com/coreybutler/nvm-windows) version which you might want to try out.

I don't think that I will add markdown support as something awesome like [Jekyll](https://jekyllrb.com/) already exist.

For linting & cache busting please do create new issues for them.

If it work for you I would like to close this issue.

**Comment by lorvent** [comment]
Hello,
thanks for the update.

let me test and update you.
