### ISSUE TITLE
how to copy node_modules files to build folder

### ISSUE THREAD

**Issue by lorvent** [nstungcom/gulp-starter-kit#9]
Hello,
can you tell me what is the proper code to write a css or js file from node_modules into build folder.

ex: bootstrap.min.js

NOTE: i have checked recipes....but my project uses 100s of js files from vendors and i want to copy them into dist/vendors so that i can include them only in required pages.

thanks.

**Comment by lorvent** [comment]
instead of using `gulp.src().pipe()`, can we have a function like this?

https://github.com/laravel/elixir/blob/master/src/tasks/recipes/copy.js

**Comment by nstungcom** [comment]
Hi, 
sorry for the late answer.. been busy with works.

For now you could use this code to copy js or css (just example):

Insert before **``.pipe(gulp.dest(`${PATHS.dist}/assets/js`))``:**
`.pipe(gulp.src('node_modules/bootstrap/js/dist/*.js', { since: gulp.lastRun(js) }))`
`.pipe(gulp.src('src/assets/js/js-copy/*.js', { since: gulp.lastRun(js) }))`

Insert before **``.pipe(gulp.dest(`${PATHS.dist}/assets/css`))``:**
`.pipe(gulp.src('node_modules/bootstrap/dist/css/*.css', { since: gulp.lastRun(js) }))`
`.pipe(gulp.src('src/assets/css/css-copy/*.css', { since: gulp.lastRun(js) }))`

You can use **config.yaml** to define multiple paths for node_modules vendors or folders example:

`.pipe(gulp.src(PATHS.jsCopy, { since: gulp.lastRun(js) }))`
`.pipe(gulp.src(PATHS.cssCopy, { since: gulp.lastRun(js) }))`

I will add this feature in the near future.

**Comment by lorvent** [comment]
Hello,
thanks, i will try it.

would be great, if you could add a function or such to copy assets.

thanks.
